panva/node-oidc-provider

README.md
lib/actions/registration.js
lib/helpers/client_schema.js
lib/models/client.js
test/configuration/client_metadata.test.js
test/dynamic_registration/dynamic_registration.test.js

Pull several improvements to registration feature into master.

optional client_secrets and registration event emit

---

README.md
example/express.js
lib/actions/authorization.js
lib/actions/authorization/check_pixy.js
lib/actions/authorization/index.js
lib/actions/authorization/process_response_types.js
lib/actions/token/authorization_code.js
lib/consts/param_list.js
lib/models/oauth_token.js
test/pkce/pkce.config.js
test/pkce/pkce.test.js

Implementation of https://tools.ietf.org/html/rfc7636

Proof Key for Code Exchange by OAuth Public Clients

---

example/index.js
example/settings.js
lib/actions/authorization/process_response_types.js
lib/actions/token/authorization_code.js
lib/actions/token/refresh_token.js
lib/helpers/oidc_context.js
lib/models/base_token.js

Passing an array of method references as amr property in result.login
with amr configured as a supported claim will make that claim available
in ID Tokens resulting from this Authentication

amr (Authentication Methods References) handling

---

docs/configuration.md

new (provider.InitialAccessToken)({}).then(console.log); should be new (provider.InitialAccessToken)({}).save().then(console.log);

fix typo of configuration.md

---

lib/actions/authorization/interactions.js
lib/helpers/defaults.js

- can be used to change the behavior of when to send user to interaction
- can be made to just pass anyone or have complex logic
- may return a Promise (similar to id_token_hint check)

interactionCheck helper function

---

lib/actions/authorization/interactions.js
lib/actions/authorization/respond.js
lib/actions/check_session.js
lib/actions/end_session.js
lib/helpers/defaults.js
lib/models/session.js
lib/provider.js
lib/shared/resume.js
lib/shared/session.js
test/claims/claims.test.js
test/session_management/end_session.test.js

- cookie names are now configurable
- cleanup of result and resume short cookies

cookie names and cleanup

---

docs/configuration.md
example/express.js

I've had problems troubleshooting setting up an OIDC application running on HTTPS. I hope that those additional explanations might help others.
And thanks for those very neat package, docs, examples, etc.
Don't hesitate to ask for any modification on this PR.

Document a bit more SSL/TLS proxifying

---

lib/actions/grants/authorization_code.js
test/pkce/pkce.test.js

Add some tests

---

docs/configuration.md
docs/update-configuration.js
example/settings.js
lib/helpers/client_schema.js
lib/helpers/defaults.js
lib/provider.js
test/configuration/custom_client_metadata.test.js

extraClientMetadata config option

---

lib/actions/interaction.js
lib/helpers/attention.js
lib/helpers/configuration.js
lib/helpers/defaults.js
lib/helpers/initialize_adapter.js
lib/helpers/initialize_app.js
lib/helpers/initialize_keystore.js
lib/provider.js
lib/shared/selective_body.js
test/capture_output.js
test/helpers/attention.test.js

It only colors the output if in a TTY
The technique used comes from https://github.com/dougwilson/nodejs-depd

Colorize console output requiring attention

---

example/adapters/bookshelf_postgresql_adapter.js

This fixes BookshelfPostgresqlAdapter example destroy and expiration
The PostgreSQL schema of the database has to be changed

Fix BookshelfPostgresqlAdapter destroy, expiration

---

README.md
docs/configuration.md
example/adapters/bookshelf_postgresql_adapter.js
example/my_adapter.js

One rationale: adding the words "custom adapter" to more easily find this point in the doc through a simple search engine search

Little doc updates on small points

---

lib/adapters/memory_adapter.js
test/configuration/adapter_test.test.js
test/models.js

Fix miss of grant object destroy

---

example/adapters/bookshelf_postgresql_adapter.js

Now all expired records are purged, not only those which are asked for through a find.
And the grant object is now removed.

In bookshelf postgresql adapter, fix expired records purge and grant object removal

---

docs/configuration.md
lib/models/session.js
lib/provider.js
test/provider/set_session_account_id.test.js

@panva This is more of a starting point so I can get your feedback on what needs to be updated or changed with the implementation of the meta argument.
Ref #352

Add metadata to setProviderSession

---

lib/models/client.js

Altho not changing any validation outcome this will remove a weird looking id token validation error.

fix: JWKStore prototype jwksUri undefined client

---

README.md
docs/README.md
example/support/configuration.js
lib/helpers/defaults.js
lib/helpers/features.js

Fixed and updated supported drafts.
I've fixed the `jwtResponseModes` feature draft version and updated `jwtIntrospection` feature draft version as I don't see any relevant change in specs.

Fixed and updated supported drafts

---

lib/actions/interaction.js
lib/helpers/initialize_app.js

* correct ssl offloading proxy url in warning

Minor fixes 

---

example/adapters/sequelize.js

Making changes for setting sequelize adapter (postgres)

[UPDATE] Adding sequelize adapter for postgres db

---

example/adapters/sequelize.js

Hi @panva,
I put the reference for the migrations as you mention before.

fix: adding sequelize migration example as comment

---

lib/response_modes/form_post.js
test/device_code/code_verification_endpoint.test.js
test/device_code/device_resume.test.js
test/interaction/interaction.test.js
test/run.js

Helps in creating a more secure CSP.

refactor: removed inline script from form post html

---

example/adapters/firestore.js
example/adapters/firestore.ts

allow the library to be used with Google's Firestore.

example: added firestore database sample

---

types/index.d.ts

in fact, this was the problem. validate from IdToken is static

fix(typescript): static IdToken.validate

---

example/adapters/dynamodb-gsi.ts
example/adapters/dynamodb.ts

DynamoDB Adapter to be used by the library.

example: add GSI DynamoDB adapter

---

recipes/README.md
recipes/skip-consent.md

Adds example in recipes on how to skip consent

docs: add skip consent recipe

---

types/index.d.ts
types/oidc-provider-tests.ts

Change typings to allow for the functional adapter creator.

feat(typescript): allows adapter factory in typings

---

certification/oidc.js

This reverts commit 2b3b1cc40d037eddc67394ba8209321b886bc8ae.

Revert "example: retrofit webfinger for cert suite issue"

---

lib/helpers/interaction_policy/prompts/login/index.js

Hello,
This should fix #853 if it is an error.

fix: missing login prompt details

---

docs/README.md
docs/checks.txt

I updated the doc in order correct the default value for `interactions.policy`.

docs: update interactions.policy default value

---

example/adapters/sequelize.js

It seems an update to node-odic added this model and it was not reflected here.

example: add Grant to Sequelize Adapter Models

---

example/adapters/knex.js

Hi,
this is an example of a [knex](http://knexjs.org/) based adapter. I use it myself. I left a comment that points to a personal repository with tests and usage examples. Feel free to remove it, the code is licensed under "The Unlicense".
I hope this can help, thank you for your work.

knex adapter

---

lib/models/base_model.js

I was inspecting the code and i noticed the name of the function was not aligned.
The fix align the function name.

Fix function name

---

example/adapters/contributed/prisma.ts

Add a fully typed Prisma adapter with a reference to an example with the oidc-provider consuming it.

example: add prisma adapter

---

example/routes/express.js

```sh
TypeError: Cannot read properties of undefined (reading 'SessionNotFound')
```

Fix TypeError in routes/express.js

---

.github/workflows/conformance.yml

Reverts panva/node-oidc-provider#1242

Revert "build(deps): bump actions/upload-artifact from 3 to 4"
