panva/node-oidc-provider

example/my_adapter.js
lib/actions/authorization/interactions.js
lib/actions/authorization/process_response_types.js
lib/helpers/defaults.js
lib/helpers/oidc_context.js
lib/models/session.js
lib/shared/resume.js
test/claims/claims.test.js

- only the authentication request ACR was negotiated for should have
higher than the fallback value
- requesting acr claim via null value no longer throws server_error

acr claim behavior fix

---

lib/actions/authorization.js
lib/helpers/defaults.js

Using new configuration option an extra set of parameters will get
recognized by the authentication endpoint, these parameters will be
included in ctx.oidc.params as well as in the _grant cookie that is
passed interaction. Resolves #37

Whitelist extra parameters for authentication

---

README.md
docs/configuration.md
lib/helpers/client_schema.js
lib/helpers/defaults.js
lib/models/client.js
test/oauth_native_apps/oauth_native_apps.config.js
test/oauth_native_apps/oauth_native_apps.test.js

A non-breaking feature flag implementing native client redirect uri validations to conform with three redirect_uri options defined in https://tools.ietf.org/html/draft-ietf-oauth-native-apps-06
Closes #46 
The way I interpret the spec, in regards to what the OP should handle.
I don't believe it's intended to be able to combine the three redirect URI options, i.e. custom uri scheme, with any hostname and dynamic ports. So, when the feature flag is provided and application_type is native the following presets should be possible:
* App-declared Custom URI Scheme Redirection
any non http/https uri scheme, with localhost as hostname and no dynamic ports
* App-claimed HTTPS URI Redirection
https with any valid (non loopback) hostname and no dynamic ports
* Loopback URI Redirection
http protocol …

OAuth 2.0 for Native Apps BCP

---

docs/configuration.md
lib/models/session.js
lib/shared/resume.js
test/backchannel_logout/backchannel_logout.test.js
test/interaction/interaction.test.js
test/test_helper.js

See #164 
I went for a free object rather than storing directly the scopes as it is a bit more flexible. Let me know.

enable metadata passing in the 'result' object stored alongside the authorization sid

---

docs/configuration.md
lib/shared/resume.js
test/interaction/interaction.test.js

See #167 
I've also added an optional  `error_status_code` field to the error object to be more consistent with other errors created by the provider. When not defined, it default to 400.

Enable primature end of an interaction via an error result object

---

README.md
lib/actions/authorization/decode_request.js
lib/helpers/jwt.js
lib/models/base_token.js
lib/models/id_token.js
lib/provider.js
lib/shared/token_jwt_auth.js
test/jwt/jsonwebtoken.test.js
test/request/jwt_request.test.js
test/token_auth/client_auth.test.js

This fixes an issue we had where client assertions and request objects
were being rejected because the systems clocks of the OP and RP
were out of alignment.
I used the same variable name and method of configuration as https://github.com/panva/node-openid-client

Allow system clock skew

---

lib/actions/introspection.js
test/introspection/introspection.test.js

The endpoint does not show any details about expired or revoked token. However, consumed token was returned with `active=false` but also with all details that could lead to security issues.
Possible BC break but no one should depend on it because it is not correct behavior.

fix returning token introspection details for consumed token

---

docs/configuration.md
lib/actions/authorization/process_response_types.js
lib/actions/grants/authorization_code.js
lib/actions/grants/refresh_token.js
lib/actions/userinfo.js
lib/helpers/claims.js
lib/helpers/defaults.js
lib/helpers/jwt.js
lib/models/id_token.js
test/backchannel_logout/backchannel_logout.test.js
test/configuration/audiences.config.js
test/configuration/audiences.test.js

**audiences**
Helper used by the OP to push additional audiences to issued ID Tokens and other signed responses. The return value should either be falsy to omit adding additional audiences or an array of strings to push.  
affects: id token audiences, signed userinfo audiences  
default value:
```js
async audiences(ctx, accountId, token) {
// token is a reference to the token used for which a given account is being loaded,
// is undefined in scenarios where claims are returned from authorization endpoint
return undefined;
}
```

Additional ID Token audiences helper

---

docs/configuration.md
lib/models/client.js
test/configuration/clients.test.js

Relates to https://github.com/panva/node-oidc-provider/issues/143.
I was not sure wether it would be preferable to add a different function or use the existing one.

add clear single client from cache

---

CHANGELOG.md
README.md
docs/configuration.md
example/index.js
lib/helpers/http/index.js
lib/helpers/initialize_app.js
lib/provider.js
package.json
test/provider/provider_instance.test.js
test/session_management/authorization.test.js
test/test_helper.js

2.15.0
- [DIFF](https://github.com/panva/node-oidc-provider/compare/v2.14.1...v2.15.0)
- add `provider.use((ctx, next) => {})` middleware support
- add `provider.listen(port_or_socket)`
- add attribute delegates `proxy`, `keys`, `env`, `subdomainOffset` from provider to the underlying koa app
- updated docs

2.15.0 changes

---

docs/configuration.md
lib/helpers/defaults.js

by using an id instead of relying on the form being the first form in the web document.
Also renaming op.logoutForm into oidc-provider.logoutForm using a kind of namespace to avoid conflict and make code browsing and discovery easier.

More resilient logout form

---

.editorconfig

The proposed file contains proposed values that can be changed, those are just propositions based on the project linting configuration.
Many projects have this config file: https://github.com/koajs/koa, https://github.com/expressjs/express/, etc.
For example I'm often using Emacs and this file makes it switch automatically from 4 spaces indent to 2 spaces indent on a project basis.

Add .editorconfig to ease recurring contributions

---

CHANGELOG.md
lib/actions/authorization/check_response_type.js
lib/actions/token.js
lib/helpers/errors.js
test/client_auth/client_auth.test.js
test/core/basic/code.authorization.test.js
test/provider/provider_class.test.js

- fixes non-spec errors `restricted_response_type` and `restricted_grant_type` to be UnauthorizedClient (`unauthorized_client`) instead as specified in RFC6749
- adds AccessDenied (`access_denied`) and TemporarilyUnavailable (`temporarily_unavailable`) errors to the list of exported errors

fix error codes

---

CHANGELOG.md
docs/configuration.md
docs/update-configuration.js
example/index.js
lib/helpers/defaults.js
lib/helpers/errors.js
lib/models/session.js
lib/provider.js
lib/shared/resume.js
test/interaction/interaction.test.js
test/provider/provider_class.test.js
test/sessions/sessions.test.js

Fixes #299
Fixes issues with interaction sessions and the back button, assertions are now in place and both resume endpoint and interaction helpers will reject with SessionNotFound named error, which is essentially just InvalidRequest with a more descriptive name.
Note that this is not graceful and the interaction implementation still needs to handle these errors.

Missing sessions and id cookies refactor

---

CHANGELOG.md
docs/configuration.md
example/settings.js
lib/actions/authorization/process_response_types.js
lib/actions/grants/authorization_code.js
lib/actions/grants/refresh_token.js
lib/helpers/configuration.js
lib/helpers/defaults.js
test/claim_types/claim_types.config.js
test/claim_types/claim_types.test.js
test/id_token_claims/conform.config.js
test/id_token_claims/conform.test.js
test/id_token_claims/non_conform.config.js
test/id_token_claims/non_conform.test.js

[Core 1.0 - 5.4. Requesting Claims using Scope Values](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims) defines that claims requested using the `scope` parameter are returned from the UserInfo Endpoint
unless the `response_type=id_token`.
> The Claims requested by the profile, email, address, and phone scope values are returned from the
> UserInfo Endpoint, as described in Section 5.3.2, when a response_type value is used that results
> in an Access Token being issued. However, when no Access Token is issued (which is the case for
> the response_type value id_token), the resulting Claims are returned in the ID Token.
To enable/disable this conform behaviour
```js
const configuration = { features: { conformIdTokenClaims: Boolean[false] } };
```
The conform/non-conform …

conform id token end-user claims feature toggle

---

lib/provider.js

Give the caller access to the session object
since they won't have access to the session
id using the normal cookie.
Figured a PR would be better than a "feature request" issue with no code, even if it is just a 1-liner.
We have a use case where we lose cookies on our client, but the session should still be active. We also use the node-oidc-provider session for add-on features, and since the cookies are lost we can't recover the session when processing a request. I can call `setProviderSession` to recover the session, but I can't figure out how to get access to the new session id to make the session available to my add-on features.

feat: return session from setProviderSession

---

docs/configuration.md
lib/provider.js

As already mentioned here #350. We have no clear way to propagate interaction result without causing response redirect. To allow custom response handling I'm submitting this non-breaking PR which simply extracts result propagation to its own method.
Now, instead of calling `provider. interactionFinished` we have option to call `provider.setInteractionResult` with same arguments to prevent immediate redirection.

feat: option to setInteractionResult without calling interactionFinished

---

lib/provider.js
package.json

This is the fix for #383 and adds support for http2 in `assertReqRes`.
The http2 module is only stable in node >= v10.0.0. Therefore http2 is only supported if node >= v10.0.0 is used.

fix: allow http2 in assertReqRes (fixes #383)

---

lib/helpers/jwt.js
lib/models/client.js
lib/models/id_token.js
lib/shared/token_auth.js
test/configuration/client_keystore.test.js

This move the staleness check (which contains a
check if a jwks_uri exists) into the refresh method.
This reduces some duplication and makes it easier
to use for people who interact with `client.keystore`.
I added an option to force a refresh, as this was
needed to enable the tests to pass.
#415

feat: make refreshing a keystore safer

---

lib/actions/authorization/process_response_types.js
test/core/hybrid/code+id_token+token.authorization.test.js
test/core/hybrid/code+token.authorization.test.js
test/core/implicit/id_token+token.authorization.test.js
test/test_helper.js

`scope` in authorization response must exist if it is not equal to the one requested by client. 
>   The authorization server MAY fully or partially ignore the scope
>    requested by the client, based on the authorization server policy or
>    the resource owner's instructions.  If the issued access token scope
>    is different from the one requested by the client, the authorization
>    server MUST include the "scope" response parameter to inform the
>    client of the actual scope granted.
See [RFC6749](https://tools.ietf.org/html/rfc6749#section-3.3)
It is stated as optional in [Section 5.1 - Issuing an Access Token - Successful Response](https://tools.ietf.org/html/rfc6749#section-5.1)
>    scope
>    &nbsp;&nbsp;&nbsp;&nbsp;OPTIONAL, if identical to the scope requested by the …

fix: add scope to implicit responses when different from request

---

lib/actions/discovery.js

Fixed enabled check conditions in `discovery.js`

Fixed enabled check conditions

---

types/index.d.ts

I'm using the Koa example to bootstrap a new project and found that this change makes my life a lot easier when using TypeScript and Koa.

refactor(typescript): use Koa.ParameterizedContext in typings

---

types/index.d.ts
types/oidc-provider-tests.ts

As discussed, the current types doesn't allow just a boolean value, only a function that returns a promise or a boolean

fix(typescript): rotateRefreshToken boolean, ES256K, async customizers

---

lib/shared/session.js

If the session is transient then legacy cookies should also be transient,
so that the session is correctly ended when the browser is closed.
NOTE: I didn't find any tests covering the session middleware, but if you point me in the right direction I can add some

fix: set samesite compatibility cookie as transient when the session is

---

types/index.d.ts

Currently, an OIDCContext is assigned at ctx.oidc. However, it's incorrectly defined in the typescript definition due to the type parameter mispositioned in ParameterizedContext.
fix #659

fix(typescript): correct KoaContextWithOIDC definition

---

types/index.d.ts

Sorry, my bad. I missed the default state and context in KoaContextWithOIDC, making it too restrictive to be extended.

fix(typescript): correct KoaContextWithOIDC definition, take 2

---

package.json
types/index.d.ts
types/oidc-provider-tests.ts

The example provided in the docs shows the [sequelize adapter returning a `consumed` property if the token has been consumed](https://github.com/panva/node-oidc-provider/blob/30e439ac525d6d10361537046ef9682d736284ea/example/adapters/sequelize.js#L69-L94), but this property is not present in the typings. This causes a TypeScript error with the latest version of TypeScript (3.8.3).
The fix here is to return a new interface from the `find*` methods of the adapter class which includes this `consumed` property, along with all of the other possible properties from`AdapterPayload`.
Additionally, a devDependency on TypeScript was added to satisy a warning when running `npm install` (`dtslint` has a peerDependency on typescript).

fix(typescript): adapter methods typings and interface name typo

---

lib/helpers/features.js

Adds the expected acknowledgement for `draft-09` for the `jwtIntrospection`.
This enables users of this library to acknowledge the proper jwt introspection draft version that this library is currently using, it further prevents users who have acknowledged `draft-08` previously from unexpectedly breaking their application when updating the library.
This MR fixes #734

fix: correct jwtIntrospection draft ack version

---

types/index.d.ts
types/oidc-provider-tests.ts

All findAccount call sites handle the possibility that a falsy value is
returned, indicating that no account was found.

fix(typescript): findAccount may return undefined

---

lib/models/client.js

The condition `!parsed.protocol === 'http:'` always returns `false`. The `!` operator has a higher precedence than the `===` operator. `parsed.protocol` is a string, so negating it would be `false`. Then, it's clear that `false === 'http:'` is always `false`.
It seems that the intended check was `parsed.protocol !== 'http:'`.

fix: loopback redirectUriAllowed protocol check

---

types/index.d.ts

Fix result typing which can be undefined when getting the interaction from `interactionDetails()`

fix(typescript): interaction result may be undefined

---

docs/README.md
lib/helpers/defaults.js

This is not the ultimate wording, but at least it clearly shows that `claims` does actually 2 kind of different things with a different syntax

docs: update the claims section

---

types/index.d.ts

Interaction.session is always a plain object - its type was changed to
a union type including Session when the Interaction constructor was
updated to handle payload.session being an instance of Session, but in
such a case, the Session object is transformed to a plain object.
The jti property appears to have been an extraneous duplicate of the
cookie property - a Session object's jti property is mapped to the
cookie property of the plain object.
The uid property was simply missing from the type definition.

fix(typescript): Interaction.prototype.session structure

---

lib/actions/grants/authorization_code.js
lib/actions/grants/ciba.js
lib/actions/grants/device_code.js
lib/actions/grants/refresh_token.js

Fixes an issue where ID tokens would not include account claims, even if the access token was not usable for the userInfo endpoint (contained an aud value).
Currently, if you use the resourceIndicators feature and issue an access token in JWT format, then the returned ID token will not contain any account claims. This is despite the fact that the JWT access token is not usable on the userInfo endpoint.
Problem is caused by the code checking the access token for an `aud` value. It's checking the generated token string rather then the original token object.

fix: correctly check access token audience when issuing ID tokens

---

certification/oidc/index.js

Just stumbled across this typo where `ctx.stats` should be `ctx.status`

example: certification code typo

---

test/dynamic_registration/dynamic_registration.test.js

while the test cases were correct the naming seems to be state
the opposite of what is expected

test: fix test naming for issue registration access token being true

---

lib/helpers/resolve_resource.js
test/resource_indicators/resource_indicators.config.js

First, thank all the contributors for your effort in building this awesome project, which helps me a lot! During my usage, I found something that maybe a minor bug. 
The `features.resourceIndicators.useGrantedResource` function defined in the config can be async function. In fact, the default value for that is indeed an async function:
https://github.com/panva/node-oidc-provider/blob/2ba83954760017caca5fe0e96e8eee2d10061e9e/lib/helpers/defaults.js#L201-L206
However, when the function is called in `resolver_resource.js`, which is used to resolve the resource for a auth or token request, the value returned by `useGrantedResource` is not awaited:
https://github.com/panva/node-oidc-provider/blob/2ba83954760017caca5fe0e96e8eee2d10061e9e/lib/helpers/resolve_resource.js#L14
In my opinion, this …

fix: await the result returned by resourceIndicators.useGrantedResource function, in resolve_resource.js

---

lib/helpers/oidc_context.js

- rollback slice to substring in oidc_context.js

fix: slice > substr(ing) in mountPath

---

recipes/skip_consent.md

…sion expiry
* currently if a session gets re-established without an explicit logout, the grantId gets copied onto the new session but its expiry does not get updated
* this means the grant can expire before the session and the interactionPolicy will try and prompt for consent
* this code snippet inspects the expiry on the session and updates the grant to match if the values differ

example: update skip_consent recipe

---

lib/helpers/client_schema.js
test/configuration/client_metadata.test.js

This PR fixed a bug introduced in [this commit](https://github.com/panva/node-oidc-provider/commit/3fca22bb5dc8dc529c08c596109988a35e110f74) which prevents using the invalidation code.

fix: invalidation code not sent

---

lib/models/interaction.js

The key for signed params was changed from `signed` to `trusted`, however unfortunately the interaction model wasn't updated and so the trusted/signed params list isn't being persisted in the interaction session.

fix: updated signed to trusted in interaction model

---

lib/helpers/initialize_adapter.js
lib/helpers/type_validators.js
lib/models/base_model.js
lib/models/client.js
test/helpers/initialize_adapter.test.js
test/helpers/type_validators.test.js
test/provider/provider_instance.test.js

Hi!
Now when implementing the "AdapterFactory" type from the package https://www.npmjs.com/package/@types/oidc-provider
a situation can happen where the types are correct, but at runtime we get an error.
I found a mention of this problem here https://github.com/panva/node-oidc-provider/pull/776#issuecomment-714742339
With this PR I add the ability to use arrow-functions and class methods as a factory and at the same time fix the non-obvious behavior when writing code in typescript

Feature: allow arrow-function & class-methods as adapter factory

---

test/test_helper.js

On Windows the `path.format` return the path of file starting with `C:`, which is a probleam on the ESM import as you can see in the log I get after running the tests
```
87) configuration features.webMessageResponseMode
"before all" hook in "configuration features.webMessageResponseMode":
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid 
file:// URLs. Received protocol 'c:'
at new NodeError (node:internal/errors:400:5)
at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1055:11)
at defaultResolve (node:internal/modules/esm/resolve:1135:3)
at nextResolve (node:internal/modules/esm/loader:163:28)
at ESMLoader.resolve (node:internal/modules/esm/loader:842:30)
at …
```

Fix test config file import on Windows

---

docs/README.md
lib/consts/client_attributes.js
test/configuration/client_metadata.test.js

Hello, I think there is a slight problem wtih `rpInitiatedLogout` configuration.
inside the `client_schema.js` there is this check at line 79
```
if (features.rpInitiatedLogout.enabled) {
RECOGNIZED_METADATA.push('post_logout_redirect_uris');
}
```
However, it looks like it does nothing, because `post_logout_redirect_uris` is already included in the default `RECOGNIZED_METADATA` array.  In order for flag `features.rpInitiatedLogout.enabled` to properly work, default recognized metadata properties should be changed.
I can't run tests locally due to `structuredClone` error, so haven't verified yet if tests don't break.

fix: ignore post_logout_redirect_uris when logout is disabled

---

lib/actions/grants/refresh_token.js

We have implemented the RBAC feature in our system based on the oidc-provider. Leveraging `resourceIndicators.getResourceServerInfo`  method to guard and filter the resource scopes being issued. 
After a user is initially sign-in and authenticated, we manually revoke a role(resource scopes) from that user. Or delete the scopes directly from that resource indicator. 
The revoked resource scopes should be filtered from the newly exchanged access tokens. 
As mentioned in the doc:
Instead of reading the latest scopes returned from the resource server, the Provider uses the initially granted resource scopes pool to issue new access tokens.  The scope can only be revoked till the user re-authenticates. 
Any 'down-scope' action should take effect immediately to the end user.  Attempt to filter …

fix: ignore non-existent resource scopes during refresh

---

docs/README.md

docs: Fix typo in `result.login` specs

---

docs/README.md

Just uses anchor link to point to specific part of discovery spec

docs: point to a specific part of Discovery 1.0 RFC

---

lib/models/client.js
test/configuration/client_metadata.test.js

Prevents "jwks" set to null in the [client metadata](https://github.com/panva/node-oidc-provider/tree/main/docs#clients) instead of a TypeError such as:
```
TypeError: Cannot read properties of null (reading 'keys')\n    at validateJWKS
(node_modules/.pnpm/oidc-provider@8.4.1/node_modules/oidc-provider/lib/models/client.js:41:29
```

fix: reject client JSON Web Key Set `null` value

---

lib/shared/check_resource.js
test/resource_indicators/client_credentials.test.js

Fix a bug in `checkResource` util function.
When checking if the resource identifier is a valid URL, we should iterate the resource array with a for-loop, and check if each identifier in the `resource` array is valid, by utilizing the `new URL()` constructor.
However, the origin code seems to mistakenly pass the entire `resource` array into the URL constructor, resulting unexpected behavior.
Fixes: https://github.com/logto-io/logto/issues/5779

fix: ensure each individual resource indicator is a valid URI

---

lib/helpers/request.js
test/helpers/request/request.config.js
test/helpers/request/request.test.js

Specifying the `user-agent` header for outgoing requests was introduced in https://github.com/panva/node-oidc-provider/commit/95f24ef6365ae54375f7459cec19fb1c6b8ba291.
This PR is fixing an issue with that commit: the `user-agent` header value set in the `httpOptions` config is not really being used, and the http agent defaults to not sending the `user-agent` HTTP header.
```javascript
const helperOptions = pickBy({ signal, agent, dnsLookup }, Boolean);
// ...
options.headers['user-agent'] = helperOptions['user-agent']; // at this point, helperOptions['user-agent'] is always undefined
```
In practice, due to the missing `user-agent`, WAFs could block requests to the `jwks_uri` endpoint during a client authentication.

fix: allow specifying the user-agent header for outgoing requests
